### ISSUE TITLE
Create user and calculate age

### ISSUE THREAD

**Issue by Mobro-corp** [maudev-bignited/huge-person-database#2]
When creating a user, there is no check for the date of birth. So an user can enter a date in the future and this will be pushed to the database.
Because of this issue, the calculate age function could possibly use the faulty birth date to calculate the age, which can output a negative number.

**Comment by E-Bresseleers** [comment]
There was no validation if the data of birth was into the future.
Implemented this code:
![afbeelding](https://github.com/maudev-bignited/huge-person-database/assets/71663755/9798f928-ac36-48bf-9514-a24baaab3fb4)

It now gives an error, telling it's not possible:
![afbeelding](https://github.com/maudev-bignited/huge-person-database/assets/71663755/4896330f-4c51-473d-9e5e-a1fd676610a4)
