### ISSUE TITLE
Update e-mail domail null variable error

### ISSUE THREAD

**Issue by tome32145** [maudev-bignited/huge-person-database#7]
1) use swagger to create post request of newdomain
2) enter new description as domain and submit

Wrong Outcome:
given error status code 500:   "message": "Cannot invoke \"String.split(String)\" because the return value of \"be.bignited.hugeuserdatabase.entity.Person.getEmail()\" is null", and no email domain was changed

expected outcome:
all emails domain are changed

**Comment by maudev-bignited** [comment]
Added null check for email domain
